/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package adminkalender;

import java.awt.Color;
import java.awt.Image;
import java.awt.Window;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
//import jdk.internal.org.jline.terminal.impl.jna.JnaSupportImpl;
import javax.swing.ImageIcon;
import jnafilechooser.api.JnaFileChooser;
import koneksi.conek;

/**
 *
 * @author USER
 */
public class profil extends javax.swing.JFrame {

    /**
     * Creates new form profil
     */
    public profil() {
        initComponents();
        setdatauser();
        txtnip.setBackground(new Color(0,0,0,0));
        txtnip.setBorder(null);
        txtnama.setBackground(new Color(0,0,0,0));
        txtnama.setBorder(null);
        txtjabatan.setBackground(new Color(0,0,0,0));
        txtjabatan.setBorder(null);
        txtno.setBackground(new Color(0,0,0,0));
        txtno.setBorder(null);
        txtemail.setBackground(new Color(0,0,0,0));
        txtemail.setBorder(null);
    }
        public void setdatauser(){
        koneksi.Orang user = new koneksi.Orang();
        String nip = user.getUsername();
       try{
            Statement statement=(Statement)conek.GetConnection().createStatement();
            ResultSet res=statement.executeQuery("SELECT * from admin where nip = '"+ nip +"'");
            while(res.next())
            {
              txtnip.setText(res.getNString("nip"));
              txtnama.setText(res.getNString("nama"));
              txtjabatan.setText(res.getNString("jabatan"));
              txtno.setText(res.getNString("no_tlp"));
              txtemail.setText(res.getNString("email"));
              
            }
        }catch (SQLException e){
               
        }      
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtnip = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        txtjabatan = new javax.swing.JTextField();
        txtno = new javax.swing.JTextField();
        txtprof = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        bedit = new javax.swing.JLabel();
        profile = new javax.swing.JLabel();
        cover = new javax.swing.JLabel();
        bprofil = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtnip.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtnip.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtnip.setEnabled(false);
        getContentPane().add(txtnip, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 322, 510, 30));

        txtnama.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtnama.setEnabled(false);
        getContentPane().add(txtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 510, 30));

        txtjabatan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtjabatan.setEnabled(false);
        getContentPane().add(txtjabatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, 510, 30));

        txtno.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtno.setEnabled(false);
        getContentPane().add(txtno, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 522, 510, 30));
        getContentPane().add(txtprof, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 330, 130, 30));

        txtemail.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtemail.setEnabled(false);
        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });
        getContentPane().add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 592, 510, 30));

        bedit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                beditMouseClicked(evt);
            }
        });
        getContentPane().add(bedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 390, 190, 30));

        profile.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 160, 170));

        cover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/Profil_jpg.png"))); // NOI18N
        getContentPane().add(cover, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        bprofil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bprofilMouseClicked(evt);
            }
        });
        getContentPane().add(bprofil, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 330, 50, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void beditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_beditMouseClicked
        // TODO add your handling code here:
        edit a = new edit();
       
        
        a.setVisible(true);
        a.pack();
        a.setDefaultCloseOperation(edit.DISPOSE_ON_CLOSE);
        
    }//GEN-LAST:event_beditMouseClicked

    private void bprofilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bprofilMouseClicked
        // TODO add your handling code here:
        JnaFileChooser fileChooser = new JnaFileChooser();
        Window Window = null;
        boolean action = fileChooser.showOpenDialog(Window);
        if (action) {
            System.out.println(fileChooser.getSelectedFile());
            File selectedFile = fileChooser.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            txtprof.setText(path);
            
            try{
                byte[] img = Files.readAllBytes(selectedFile.toPath());
                ImageIcon imageIcon = new ImageIcon(img);
                
                int labelWidht = 160;
                int labelHeight = 170;
                
                int imageWidht = imageIcon.getIconWidth();
                int imageHeight = imageIcon.getIconHeight();
                
                double scaleX =  (double) labelWidht / (double) imageWidht;
                double scaleY =  (double) labelHeight / (double) imageHeight;
                double scale = Math.min(scaleY, scaleY);
                
                Image scaledImage = imageIcon.getImage().getScaledInstance((int) (scale * imageWidht), (int) (scale * imageHeight), Image.SCALE_SMOOTH);
                
               profile.setIcon(new ImageIcon(scaledImage));
            }catch (IOException ex){
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_bprofilMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(profil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(profil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(profil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(profil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new profil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bedit;
    private javax.swing.JLabel bprofil;
    private javax.swing.JLabel cover;
    private javax.swing.JLabel profile;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtjabatan;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnip;
    private javax.swing.JTextField txtno;
    private javax.swing.JTextField txtprof;
    // End of variables declaration//GEN-END:variables
}
